version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:5.0.8
    restart: always
    container_name: redis
    volumes:
      - "/var/lib/docker/volumes/redis/data:/data:z"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    entrypoint: docker-entrypoint.sh --requirepass ${REDIS_PASSWORD}

  app:
    image: vieir4ndo/cu-uffs:latest
    container_name: app
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ..:/var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      CONTAINER_ROLE: app
    entrypoint: ./docker/start.sh

  horizon:
    image: vieir4ndo/cu-uffs:latest
    container_name: horizon
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - ..:/var/www/html
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: horizon
    entrypoint: ./docker/start.sh

  scheduler:
    image: vieir4ndo/cu-uffs:latest
    container_name: scheduler
    restart: always
    ports:
      - '8002:8002'
    volumes:
      - ..:/var/www/html
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: scheduler
    entrypoint: ./docker/start.sh

  webpacker:
    image: vieir4ndo/cu-uffs:latest
    container_name: webpacker
    restart: always
    command: 'npm run watch'
    ports:
      - '8003:8003'
    volumes:
      - ..:/var/www/html
    depends_on:
      - app

networks:
  snr:
    ipam:
      driver: default
