<?php

return [
    'chapeco' => [
        "1600" => "ADMINISTRAÇÃO",
        "1601" => "ADMINISTRAÇÃO",
        "1501" => "AGRONOMIA",
        "1101" => "CIÊNCIA DA COMPUTAÇÃO",
        "1100" => "CIÊNCIA DA COMPUTAÇÃO",
        "1740" => "CIÊNCIAS SOCIAIS",
        "1741" => "CIÊNCIAS SOCIAIS",
        "1400" => "ENFERMAGEM",
        "1301" => "ENGENHARIA AMBIENTAL E SANITÁRIA",
        "1700" => "FILOSOFIA",
        "1701" => "FILOSOFIA",
        "1711" => "GEOGRAFIA",
        "1710" => "GEOGRAFIA",
        "1720" => "HISTÓRIA",
        "1721" => "HISTÓRIA",
        "1800" => "LETRAS PORTUGUÊS E ESPANHOL",
        "1801" => "LETRAS PORTUGUÊS E ESPANHOL",
        "1110" => "MATEMÁTICA",
        "1411" => "MEDICINA",
        "1730" => "PEDAGOGIA",
        "1731" => "PEDAGOGIA",
    ],
    "laranjeiras" => [
        "2503" => "AGRONOMIA",
        "2202" => "CIÊNCIAS BIOLÓGICAS",
        "2601" => "CIÊNCIAS ECONÔMICAS",
        "2713" => "CIÊNCIAS SOCIAIS",
        "2714" => "CIÊNCIAS SOCIAIS",
        "2521" => "DESENVOLVIMENTO RURAL E GESTÃO AGROINDUSTRIAL",
        "2310" => "ENGENHARIA DE ALIMENTOS",
        "2510" => "ENGENHARIA DE AQUICULTURA",
        "2531" => "INTERDISCIPLINAR EM EDUCAÇÃO DO CAMPO: CIÊNCIAS DA NATUREZA",
        "2541" => "INTERDISCIPLINAR EM EDUCAÇÃO DO CAMPO: CIÊNCIAS NATURAIS, MATEMÁTICA E CIÊNCIAS AGRÁRIAS",
        "2540" => "INTERDISCIPLINAR EM EDUCAÇÃO DO CAMPO: CIÊNCIAS NATURAIS, MATEMÁTICA E CIÊNCIAS AGRÁRIAS",
        "2550" => "INTERDISCIPLINAR EM EDUCAÇÃO DO CAMPO: CIÊNCIAS SOCIAIS E HUMANAS",
        "2703" => "PEDAGOGIA",
    ],
    "realeza" => [
        "3602" => "ADMINISTRAÇÃO PÚBLICA",
        "3201" => "CIÊNCIAS BIOLÓGICAS",
        "3111" => "CIÊNCIAS NATURAIS",
        "3101" => "FÍSICA",
        "3803" => "LETRAS PORTUGUÊS E ESPANHOL",
        "3530" => "MEDICINA VETERINÁRIA",
        "3410" => "NUTRIÇÃO",
        "3704" => "PEDAGOGIA",
        "3121" => "QUÍMICA",
    ],
    "cerro_lago" => [
        "4601" => "ADMINISTRAÇÃO",
        "4500" => "AGRONOMIA",
        "4110" => "CIÊNCIAS: BIOLOGIA, FÍSICA E QUÍMICA",
        "4200" => "CIÊNCIAS BIOLÓGICAS",
        "4520" => "DESENVOLVIMENTO RURAL E GESTÃO AGROINDUSTRIAL",
        "4300" => "ENGENHARIA AMBIENTAL E SANITÁRIA",
        "4100" => "FÍSICA",
        "4802" => "LETRAS PORTUGUÊS E ESPANHOL",
        "4131" => "MATEMÁTICA",
        "4120" => "QUÍMICA",
    ],
    "erechim" => [
        "5502" => "AGRONOMIA",
        "5524" => "AGRONOMIA",
        "5610" => "ARQUITETURA E URBANISMO",
        "5203" => "CIÊNCIAS BIOLÓGICAS",
        "5742" => "CIÊNCIAS SOCIAIS",
        "5302" => "ENGENHARIA AMBIENTAL E SANITÁRIA",
        "5702" => "FILOSOFIA",
        "5713" => "GEOGRAFIA",
        "5712" => "GEOGRAFIA",
        "5722" => "HISTÓRIA",
        "5723" => "HISTÓRIA",
        "5510" => "INTERDISCIPLINAR EM EDUCAÇÃO DO CAMPO: CIÊNCIAS DA NATUREZA",
        "5732" => "PEDAGOGIA",
    ],
    "passo_fundo" => [
        "5502" => "AGRONOMIA",
        "5524" => "AGRONOMIA",
        "5610" => "ARQUITETURA E URBANISMO",
        "5203" => "CIÊNCIAS BIOLÓGICAS",
        "5742" => "CIÊNCIAS SOCIAIS",
        "5302" => "ENGENHARIA AMBIENTAL E SANITÁRIA",
        "5702" => "FILOSOFIA",
        "5713" => "GEOGRAFIA",
        "5712" => "GEOGRAFIA",
        "5722" => "HISTÓRIA",
        "5723" => "HISTÓRIA",
        "5510" => "INTERDISCIPLINAR EM EDUCAÇÃO DO CAMPO: CIÊNCIAS DA NATUREZA",
        "5732" => "PEDAGOGIA",
    ]
];
